#!/bin/bash
sourcedir="/etc/openvpn-configs"
targetdir="/etc/openvpn"
loginfile="/root/vpn-login.conf"

if [ "$1 " == " " ]; then
		echo "Please specify filename"
		exit 1
fi

filename=$(basename $1)
servername="${filename%.*}"
targetfile="$targetdir/$servername.conf"
loginfile_sed=$(echo $loginfile | sed -e 's/[\/&]/\\&/g')

rm $targetdir/*.conf
cp $sourcedir/$filename $targetfile
sed -i "s/auth-user-pass/auth-user-pass $loginfile_sed/g" $targetfile

service openvpn restart 

